version: "3"

services:
    app:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/fpm/conf.d/php.ini:/usr/local/etc/php/php.ini
            - ./docker/fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        links:
            -   mysql
        restart: unless-stopped
        container_name: "${APP_NAME}"
        user: "1000:1000"

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8082:80"
        restart: unless-stopped
        depends_on:
            - app
        volumes:
            - ./:/var/www/html
        container_name: "${APP_NAME}-nginx"

    npm:
      image: node:latest
      container_name: "${APP_NAME}-npm"
      volumes:
        - ./:/var/www/html
      working_dir: /var/www/html
      entrypoint: [ 'npm' ]

    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
